### PR TITLE
convert to int when given str

### PR DESCRIPTION
**Pull request by nicmcd**

### CODE REVIEW

**Comment by alexgolec** [comment]
`str` -> `int` conversion is purposefully left to the user. Also, if we want to automatically convert, we'll need to be consistent across all methods that take account IDs

**Comment by nicmcd** [comment]
This is currently causing problems. I'm able to use a string based account_id for other functions, but if I use a string based account_id when creating the Utils object, the comparison to self._account_id fails. See here:
https://github.com/alexgolec/tda-api/blob/master/tda/utils.py#L99

That is a int compared with a string, which always fails. You should either allow fluid types or not, but currently it is mixed in the expectations.

**Comment by nicmcd** [comment]
Also, if you have to choose, you should stick with strings. TDA has not guaranteed that all accounts will have numeric values. This happens to be true. Strings work everywhere.

**Comment by alexgolec** [comment]
This is a fair point, actually. Feel free to open a ticket and I'll do the work required to make it consistent.

**Pull request closed without merging**
