### PR TITLE
Order query statuses

### LINKED ISSUE #169: get_orders_by_query() with multiple statuses leads to HTTP 400 "error" :  is not a valid Order
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
When attempting to query orders with multiple statuses such as FILLED and QUEUED , a 400 "error" : "'FILLED,QUEUED' is not a valid Order Status.... is returned as the response. 

**Code to Reproduce**
```
client = tda.auth.client_from_token_file(token_path, api_key)

my_statuses = [
    tda.client.Client.Order.Status.FILLED,
    tda.client.Client.Order.Status.QUEUED,
]

orders = client.get_orders_by_query(statuses=my_statuses)
print(orders.content)  # "error" : "\'FILLED,QUEUED\' is not a valid Order Status.
```
**Expected Behavior**
Expected the function to return a HTTP 200 Response object with orders containing the input statuses

**Actual Behavior**
Returned HTTP 400 Response indicating an error with the formatting of the query

**Error/Exception Log, If Applicable**
[bug.log](https://github.com/alexgolec/tda-api/files/5974956/bug.log)

### PR DESCRIPTION
**Pull request by ray310**
Fixes #169

Addressing what seems to be an issue with get_orders_by_query() when using multiple order statuses. Hope this is helpful.

### CODE REVIEW

**Comment by bob-mcrae** [comment]
I have tested the proposed change locally and find that it does NOT return orders of all the specified statuses.  It returns the first specified status, but ignores the rest.

**Comment by ray310** [comment]
@bob-mcrae, 

Thanks for the feedback. I am going to take a look into this.

**Comment by bob-mcrae** [comment]
Hey Alex,

After fuller investigation, the issue appears to be associated with the TDA
API; there does not seem to be a way to specify more than a single status.
Really unfortunate.

**Comment by ray310** [comment]
Thanks for looking into this. I am going to close the PR.

**Pull request closed without merging**
