### PR TITLE
Allow streaming on versions below 3.8, but commit to 3.8 for testing

### PR DESCRIPTION
**Pull request by alexgolec**

### CODE REVIEW

**Comment by nicmcd** [comment]
How about explicitly using "python3.8" in Makefile?

**Comment by alexgolec** [comment]
Eh, I'm hesitant to preclude users of future python versions. Also even in a virtualenv users may still have 3.8 installed and be confused by errors around missing dependencies.

**Comment by nicmcd** [comment]
Good point. Follow up question... Why does the Makefile sometimes use "python" and sometimes use "python3"?

**Comment by alexgolec** [comment]
That is a very good question. Fixed.

**Pull request merged**
