### PR TITLE
issue #175: always pass symbols to api as uppercase, added some tests

### PR DESCRIPTION
**Pull request by zhangted**

### CODE REVIEW

**Comment by alexgolec** [comment]
Thanks for submitting this PR. Please add a test for each method in the HTTP and streaming clients.

**Comment by alexgolec** [comment]
Test looks good, please add tests for the remaining methods and I think we'll be good to go.

**Comment by zhangted** [comment]
Hey, are there more tests I should add?

**Comment by alexgolec** [comment]
Now it looks a little over-tested. Let's discuss on discord? https://discord.com/invite/nfrd9gh

**Pull request closed without merging**
